services:
  app:
    image: python-backend-hw3:latest
    build:
      context: ../
      dockerfile: ./docker/dockerfile
    container_name: app
    restart: always
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ../prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
